version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      # env_file:
      #   - .env.stage.dev
      # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000
    # environment:
    #   DB_HOST: ${DB_HOST}
    #   DB_PORT: ${DB_PORT}
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: pg_container
    image: postgres
    restart: always
    # env_file:
    #   - .env.stage.dev
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task-app
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kritsana.pr.41@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
